apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: user-grpc
  annotations:
    github.com/project-slug: kazmerdome/demo-company-go-monorepo
spec:
  type: service
  owner: group:product-team
  lifecycle: production
