apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment-gateway
  annotations:
    github.com/project-slug: kazmerdome/demo-company-go-monorepo
spec:
  type: service
  owner: group:monetization-team
  lifecycle: production
