apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: core-product-library
  annotations:
    github.com/project-slug: kazmerdome/demo-company-go-monorepo
spec:
  type: library
  owner: group:product-team
  lifecycle: production
  system: go-platform
