apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: payment-cli
  annotations:
    github.com/project-slug: kazmerdome/demo-company-go-monorepo
spec:
  type: tool
  owner: group:monetization-team
  lifecycle: production
  system: go-platform