apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: cohort-worker
  annotations:
    github.com/project-slug: kazmerdome/demo-company-go-monorepo
spec:
  type: service
  owner: group:data-science-team
  lifecycle: production
  dependsOn:
    - core-data-science-library
    - core-product-library
