apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: core-monetization-library
  annotations:
    github.com/project-slug: kazmerdome/demo-company-go-monorepo
spec:
  type: library
  owner: group:monetization-team
  lifecycle: production
